language: go
go:
  - 1.6.3

env:
  global:
    - KAFKA_PEERS=localhost:9091,localhost:9092,localhost:9093,localhost:9094,localhost:9095
    - ZOOKEEPER_PEERS=localhost:2181,localhost:2182,localhost:2183,localhost:2184,localhost:2185
    - KAFKA_INSTALL_ROOT=/home/travis/kafka
    - KAFKA_HOSTNAME=localhost
    - DEBUG=true
  matrix:
    - KAFKA_VERSION=0.8.2.2
    - KAFKA_VERSION=0.9.0.1

before_install:
  - export REPOSITORY_ROOT=${TRAVIS_BUILD_DIR}/vendor/github.com/Shopify/sarama
  - vendor/github.com/Shopify/sarama/vagrant/install_cluster.sh
  - vendor/github.com/Shopify/sarama/vagrant/boot_cluster.sh
  - vendor/github.com/Shopify/sarama/vagrant/create_topics.sh
  # Install coveralls.io dependencies
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/pierrre/gotestcover

script:
 - $HOME/gopath/bin/gotestcover -v -covermode=atomic -parallelpackages=1 -coverprofile=cover.out -timeout=5m ./... -check.vv
 - $HOME/gopath/bin/goveralls -coverprofile=cover.out -service=travis-ci
# TODO Uncomment when vet stops checking the `vendor` directory
# - make vet
 - make fmt

sudo: false
